# Generated by Django 5.1.3 on 2025-07-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagehit',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='pagehit',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='pagehit',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
