# Generated by Django 5.1.3 on 2025-07-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_created_pagehit_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagehit',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='pagehit',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagehit',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
