# Generated by Django 5.1.3 on 2025-07-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_timestamp_pagehit_created_pagehit_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehit',
            name='referer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
